# Generated by Django 2.2.10 on 2020-11-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название дисциплины')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'db_table': 'disciplines',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название стандарта')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='rating.Discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Норматив',
                'db_table': 'standards',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата соревнований')),
                ('horse_name', models.CharField(max_length=64, verbose_name='Лошадь')),
                ('athlete_name', models.CharField(max_length=128, verbose_name='Спортсмен')),
                ('club_name', models.CharField(max_length=64, verbose_name='Клуб')),
                ('fulfilled_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='rating.Standard', verbose_name='Норматив')),
            ],
            options={
                'verbose_name': 'Выполнившие норматив',
                'db_table': 'results',
            },
        ),
        migrations.CreateModel(
            name='ExcelTableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='C:\\Users\\Lab_pc\\Documents\\GitHub\\equestrian-rating\\uploads', verbose_name='Файл с результатами')),
                ('to_standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excel_files', to='rating.Standard', verbose_name='Файл таблицы со выполненными нормативами')),
            ],
            options={
                'verbose_name': 'Файл с выполненным нормативом',
                'db_table': 'excel_files',
            },
        ),
    ]
