# Generated by Django 2.2.10 on 2020-12-27 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Дисциплина', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='exceltablefile',
            options={'verbose_name': 'Файл с выполненными нормативами', 'verbose_name_plural': 'Файлы с выполненными нормативами'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Выполнивший норматив', 'verbose_name_plural': 'Выполнившие норматив'},
        ),
        migrations.AlterModelOptions(
            name='standard',
            options={'verbose_name': 'Норматив', 'verbose_name_plural': 'Нормативы'},
        ),
        migrations.RemoveField(
            model_name='exceltablefile',
            name='to_standard',
        ),
        migrations.AddField(
            model_name='exceltablefile',
            name='to_discipline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='excel_files', to='rating.Discipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exceltablefile',
            name='file',
            field=models.FileField(upload_to='D:\\Documents\\Bomzheg\\Documents\\GitHub\\equestrian-rating\\uploads', verbose_name='Файл с результатами'),
        ),
    ]
