# Generated by Django 2.2.10 on 2020-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20201227_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='description',
            field=models.CharField(max_length=512, null=True, verbose_name='Описание'),
        ),
    ]
