# Generated by Django 2.2.10 on 2020-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_standard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='club_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Клуб'),
        ),
    ]
