# Generated by Django 2.2.10 on 2021-01-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20201228_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='link',
            field=models.CharField(default='', max_length=64, verbose_name='Название для ссылки'),
            preserve_default=False,
        ),
    ]
