# Generated by Django 2.2.10 on 2021-01-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_discipline_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard',
            name='link',
            field=models.CharField(default='', max_length=64, verbose_name='Имя для ссылки'),
            preserve_default=False,
        ),
    ]
