# Generated by Django 3.1.7 on 2021-04-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_standard_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltablefile',
            name='file',
            field=models.FileField(upload_to='C:\\Users\\Ychebyshev\\IdeaProjects\\equestrian-rating\\uploads', verbose_name='Файл с результатами'),
        ),
    ]
